"""AI agent module for JDO."""

from jdo.ai.agent import (
    SYSTEM_PROMPT,
    JDODependencies,
    create_agent,
    create_agent_with_model,
    get_model_identifier,
)
from jdo.ai.context import (
    MAX_CONTEXT_MESSAGES,
    build_context,
    format_conversation,
    format_message,
    get_system_prompt,
    stream_response,
)
from jdo.ai.dates import (
    DEFAULT_TIME,
    ParseError,
    VagueDateError,
    parse_date,
    parse_datetime,
    parse_time,
)
from jdo.ai.extraction import (
    MILESTONE_EXTRACTION_PROMPT,
    MILESTONE_LINKAGE_PROMPT,
    SUGGEST_METRICS_PROMPT,
    SUGGEST_MILESTONES_PROMPT,
    VISION_EXTRACTION_PROMPT,
    VISION_LINKAGE_PROMPT,
    ExtractedCommitment,
    ExtractedGoal,
    ExtractedMilestone,
    ExtractedTask,
    ExtractedVision,
    create_extraction_agent,
    extract_commitment,
    extract_goal,
    extract_milestone,
    extract_task,
    extract_vision,
    get_missing_fields,
)

__all__ = [
    "DEFAULT_TIME",
    "MAX_CONTEXT_MESSAGES",
    "MILESTONE_EXTRACTION_PROMPT",
    "MILESTONE_LINKAGE_PROMPT",
    "SUGGEST_METRICS_PROMPT",
    "SUGGEST_MILESTONES_PROMPT",
    "SYSTEM_PROMPT",
    "VISION_EXTRACTION_PROMPT",
    "VISION_LINKAGE_PROMPT",
    "ExtractedCommitment",
    "ExtractedGoal",
    "ExtractedMilestone",
    "ExtractedTask",
    "ExtractedVision",
    "JDODependencies",
    "ParseError",
    "VagueDateError",
    "build_context",
    "create_agent",
    "create_agent_with_model",
    "create_extraction_agent",
    "extract_commitment",
    "extract_goal",
    "extract_milestone",
    "extract_task",
    "extract_vision",
    "format_conversation",
    "format_message",
    "get_missing_fields",
    "get_model_identifier",
    "get_system_prompt",
    "parse_date",
    "parse_datetime",
    "parse_time",
    "stream_response",
]
