"""add_integrity_protocol.

Revision ID: 2b2f32bb1c9f
Revises:
Create Date: 2025-12-17 22:08:31.244609

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b2f32bb1c9f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "COMMITMENT", "GOAL", "TASK", "VISION", "MILESTONE", "UNKNOWN", name="entitytype"
            ),
            nullable=False,
        ),
        sa.Column("partial_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stakeholders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PERSON", "TEAM", "ORGANIZATION", "SELF", name="stakeholdertype"),
            nullable=False,
        ),
        sa.Column("contact_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("narrative", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timeframe", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("why_it_matters", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ACHIEVED", "EVOLVED", "ABANDONED", name="visionstatus"),
            nullable=False,
        ),
        sa.Column("next_review_date", sa.Date(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("problem_statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("solution_vision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("motivation", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_goal_id", sa.Uuid(), nullable=True),
        sa.Column("vision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ON_HOLD", "ACHIEVED", "ABANDONED", name="goalstatus"),
            nullable=False,
        ),
        sa.Column("next_review_date", sa.Date(), nullable=True),
        sa.Column("review_interval_days", sa.Integer(), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vision_id"],
            ["visions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "MISSED", name="milestonestatus"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurring_commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deliverable_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stakeholder_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("due_time", sa.Time(), nullable=True),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "recurrence_type",
            sa.Enum("DAILY", "WEEKLY", "MONTHLY", "YEARLY", name="recurrencetype"),
            nullable=False,
        ),
        sa.Column("interval", sa.Integer(), nullable=False),
        sa.Column("days_of_week", sa.JSON(), nullable=True),
        sa.Column("day_of_month", sa.Integer(), nullable=True),
        sa.Column("week_of_month", sa.Integer(), nullable=True),
        sa.Column("month_of_year", sa.Integer(), nullable=True),
        sa.Column(
            "end_type", sa.Enum("NEVER", "AFTER_COUNT", "BY_DATE", name="endtype"), nullable=False
        ),
        sa.Column("end_after_count", sa.Integer(), nullable=True),
        sa.Column("end_by_date", sa.Date(), nullable=True),
        sa.Column("task_templates", sa.JSON(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status", sa.Enum("ACTIVE", "PAUSED", name="recurringcommitmentstatus"), nullable=False
        ),
        sa.Column("last_generated_date", sa.Date(), nullable=True),
        sa.Column("instances_generated", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stakeholder_id"],
            ["stakeholders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commitments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deliverable", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("stakeholder_id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("milestone_id", sa.Uuid(), nullable=True),
        sa.Column("recurring_commitment_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("due_time", sa.Time(), nullable=False),
        sa.Column("timezone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "AT_RISK",
                "COMPLETED",
                "ABANDONED",
                name="commitmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("marked_at_risk_at", sa.DateTime(), nullable=True),
        sa.Column("completed_on_time", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recurring_commitment_id"], ["recurring_commitments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["stakeholder_id"],
            ["stakeholders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "SKIPPED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("sub_tasks", sa.JSON(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_notification_task", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["commitments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cleanup_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commitment_id", sa.Uuid(), nullable=False),
        sa.Column("impact_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mitigation_actions", sa.JSON(), nullable=True),
        sa.Column("notification_task_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "IN_PROGRESS",
                "COMPLETED",
                "SKIPPED",
                "CANCELLED",
                name="cleanupplanstatus",
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("skipped_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commitment_id"],
            ["commitments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["notification_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cleanup_plans")
    op.drop_table("tasks")
    op.drop_table("commitments")
    op.drop_table("recurring_commitments")
    op.drop_table("milestones")
    op.drop_table("goals")
    op.drop_table("visions")
    op.drop_table("stakeholders")
    op.drop_table("drafts")
    # ### end Alembic commands ###
